package persist;
// Generated 18-apr-2013 11:25:59 by Hibernate Tools 3.2.1.GA



/**
 * Ipadressen generated by hbm2java
 */
public class Ipadressen  implements java.io.Serializable {


     private Integer ipId;
     private int gebrId;
     private String ipAdres;

    public Ipadressen() {
    }

    public Ipadressen(int gebrId, String ipAdres) {
       this.gebrId = gebrId;
       this.ipAdres = ipAdres;
    }
   
    public Integer getIpId() {
        return this.ipId;
    }
    
    public void setIpId(Integer ipId) {
        this.ipId = ipId;
    }
    public int getGebrId() {
        return this.gebrId;
    }
    
    public void setGebrId(int gebrId) {
        this.gebrId = gebrId;
    }
    public String getIpAdres() {
        return this.ipAdres;
    }
    
    public void setIpAdres(String ipAdres) {
        this.ipAdres = ipAdres;
    }




}


